const express = require("express");
const router = express.Router();
const PDFDocument = require("pdfkit");
const ClaimFile = require("../Models/document_tbl");

/**
 * GET /claim/:id/dossier
 * Generates a full Claim Dossier PDF
 */
router.get("/claim/:id/dossier", async (req, res) => {
  try {
    const claim = await ClaimFile.findById(req.params.id);

    if (!claim) {
      return res.status(404).json({ success: false, message: "Claim not found" });
    }

    // Set response headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=Claim_Dossier_${claim._id}.pdf`
    );

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // ---------------- HEADER ----------------
    doc
      .fontSize(20)
      .text("CLAIM DOSSIER", { align: "center" })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .text(`Claim ID: ${claim._id}`)
      .text(`Uploaded File: ${claim.fileName}`)
      .text(`Created At: ${claim.createdAt.toDateString()}`)
      .moveDown();

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // ---------------- PRESCRIPTION ----------------
    doc.fontSize(14).text("1. Prescription Details", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).text(claim.aiAnalysis.prescription || "Not found");
    doc.moveDown();

    // ---------------- LAB REPORTS ----------------
    doc.fontSize(14).text("2. Lab Reports", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).text(claim.aiAnalysis.labReports || "Not found");
    doc.moveDown();

    // ---------------- HOSPITAL BILLS ----------------
    doc.fontSize(14).text("3. Hospital Bills", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).text(claim.aiAnalysis.hospitalBills || "Not found");
    doc.moveDown();

    // ---------------- POLICY DETAILS ----------------
    doc.fontSize(14).text("4. Policy Details", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).text(claim.aiAnalysis.policyDetails || "Not found");
    doc.moveDown();

    // ---------------- MISSING INFO ----------------
    doc.fontSize(14).text("5. Missing / Clarifications", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10).text(claim.aiAnalysis.missingInformation || "None");
    doc.moveDown();

    // Footer
    doc
      .fontSize(9)
      .text(
        "Generated by ClaimSathi AI • For internal & audit purposes",
        { align: "center" }
      );

    doc.end();
  } catch (err) {
    console.error("Dossier PDF Error:", err);
    res.status(500).json({ success: false, message: "PDF generation failed" });
  }
});

module.exports = router;
