import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { 
  CheckCircle, 
  AlertTriangle,
  FileText,
  IndianRupee,
  Minus,
  ArrowRight,
  Download,
  Info,
  ChevronDown,
  ChevronUp
} from "lucide-react";
import { HealthcareButton } from "@/components/ui/healthcare-button";
import { HealthcareCard, HealthcareCardHeader, HealthcareCardTitle, HealthcareCardContent } from "@/components/ui/healthcare-card";
import Header from "@/components/layout/Header";
import ChatBot from "@/components/chatbot/ChatBot";

const ClaimDecision = () => {
  const navigate = useNavigate();
  const [showRiskDetails, setShowRiskDetails] = useState(false);

// 1. Get the real data from the previous page's work
  const rawResult = window.sessionStorage.getItem("claimResult");
  const result = rawResult ? JSON.parse(rawResult) : null;

  // 2. Map the Agent results to your UI components
const missingDocuments = (() => {
  const missing = result?.claimSummary?.missingInformation;

  // 1. If it's null, undefined, or says "none/not found", return an empty list
  if (
    !missing || 
    missing.toLowerCase() === "none" || 
    missing.toLowerCase() === "not found" || 
    missing.toLowerCase() === "no missing information"
  ) {
    return [];
  }

  // 2. If it's a string sentence, turn it into a list
  if (typeof missing === "string") {
    return missing.split(/[.,]/).filter(item => item.trim().length > 0);
  }

  return Array.isArray(missing) ? missing : [];
})();
 const hasMissingDocs = missingDocuments.length > 0;

const riskConfig = {
  title: hasMissingDocs ? "High Risk Level" : `${result?.riskAssessment?.riskLevel || "Low"} Risk Level`,
  colorClass: hasMissingDocs ? "text-destructive" : "text-success",
  bgClass: hasMissingDocs ? "bg-destructive/20" : "bg-success/20",
  iconColor: hasMissingDocs ? "text-destructive" : "text-success"
};



  const claimData = result ? {
    id: result.claimId.substring(result.claimId.length - 8).toUpperCase(),
    status: result.eligibility?.status || "UNKNOWN",
    totalBill: result.deductions.totalClaimed,
    approvedAmount: result.deductions.totalPayable,
    deductionAmount: result.deductions.totalClaimed - result.deductions.totalPayable,
    deductions: result.deductions.deductions.map((d: any) => ({
      item: d.item,
      amount: d.amount,
      reason: d.reason
    })),
    timeline: [
      { step: "Verification Agent", time: "Complete", status: "complete" },
      { step: "Eligibility Agent", time: "Complete", status: "complete" },
      { step: "Deduction Agent", time: "Complete", status: "complete" },
      { step: "Risk Assessment", time: "Complete", status: "complete" }
    ],
    riskAlert: {
  title: riskConfig.title, // Uses our new dynamic title
  description: hasMissingDocs
    ? `Claim at risk due to missing: ${missingDocuments.join(", ")}.`
    : result.riskAssessment.reasons.join(". ")
}
} : null;

  // 3. Safety check: If for some reason there is no data
  if (!claimData) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p>No claim data found. Please restart the analysis.</p>
      </div>
    );
  }

  const handleDownloadDossier = () => {
  const report = `
  CLAIM ANALYSIS REPORT - ID: ${claimData.id}
  -------------------------------------------
  STATUS: ${claimData.status}
  TOTAL CLAIMED: ₹${claimData.totalBill}
  APPROVED AMOUNT: ₹${claimData.approvedAmount}
  
  AGENT VERIFICATION:
  ${result.verification?.notes?.join("\n  ") || "All documents verified."}
  
  DEDUCTIONS IDENTIFIED:
  ${claimData.deductions.map(d => `- ${d.item}: ₹${d.amount} (${d.reason})`).join("\n  ")}
  
  RISK ASSESSMENT:
  Level: ${claimData.riskAlert.title}
  Details: ${claimData.riskAlert.description}
  -------------------------------------------
  Generated by ClaimSathi AI
  `;

  const element = document.createElement("a");
  const file = new Blob([report], {type: 'text/plain'});
  element.href = URL.createObjectURL(file);
  element.download = `Claim_Report_${claimData.id}.txt`;
  document.body.appendChild(element);
  element.click();
};
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4">
          <div className="max-w-5xl mx-auto">
            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="text-center mb-8"
            >
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ type: "spring", stiffness: 500, delay: 0.2 }}
                className="w-20 h-20 rounded-full bg-success/20 flex items-center justify-center mx-auto mb-4"
              >
                <CheckCircle className="w-10 h-10 text-success" />
              </motion.div>
              <h1 className="text-3xl font-bold text-foreground mb-2">
                {claimData.status === "ELIGIBLE"
                  ? "Claim Approved"
                  : "Claim Partially Approved"}
              </h1>
              <p className="text-muted-foreground">
                Claim ID: {claimData.id}
              </p>
            </motion.div>
            {/* Missing Documents Warning */}
{/* Only show if there are actual missing documents */}
{missingDocuments.length > 0 && (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ delay: 0.05 }}
    className="mb-8"
  >
    <HealthcareCard variant="warning" padding="default">
      <div className="flex items-start gap-4">
        <div className="w-10 h-10 rounded-xl bg-destructive/20 flex items-center justify-center shrink-0">
          <AlertTriangle className="w-5 h-5 text-destructive" />
        </div>

        <div className="flex-1">
          <h3 className="font-semibold text-foreground mb-2">
            Documents Missing – Claim at Risk
          </h3>

          <p className="text-sm text-muted-foreground mb-2">
            The following required documents were not found in your upload:
          </p>

          <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1">
            {missingDocuments.map((doc: string, index: number) => (
              <li key={index}>{doc}</li>
            ))}
          </ul>

          <p className="text-sm text-muted-foreground mt-3">
            Uploading these documents can improve approval chances and reduce delays.
          </p>
        </div>
      </div>
    </HealthcareCard>
  </motion.div>
)}


            {/* Risk Alert */}
            {claimData.riskAlert && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="mb-8"
              >
                <HealthcareCard variant="warning" padding="default">
                  <div className="flex items-start gap-4">
                    <div className="w-10 h-10 rounded-xl bg-destructive/20 flex items-center justify-center shrink-0">
                      <AlertTriangle className="w-5 h-5 text-destructive" />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <h3 className="font-semibold text-foreground">
                          {claimData.riskAlert.title}
                        </h3>
                        <button
                          onClick={() => setShowRiskDetails(!showRiskDetails)}
                          className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
                        >
                          {showRiskDetails ? "Hide" : "Details"}
                          {showRiskDetails ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        </button>
                      </div>
                      {showRiskDetails && (
                        <motion.p
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: "auto" }}
                          className="text-muted-foreground mt-2"
                        >
                          {claimData.riskAlert.description}
                        </motion.p>
                      )}
                    </div>
                  </div>
                </HealthcareCard>
              </motion.div>
            )}

            <div className="grid lg:grid-cols-5 gap-8">
              {/* Left Panel - Amount Summary */}
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2 }}
                className="lg:col-span-2 space-y-6"
              >
                {/* Total Bill */}
                <HealthcareCard variant="elevated" padding="lg">
                  <HealthcareCardContent>
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-10 h-10 rounded-xl bg-muted flex items-center justify-center">
                        <FileText className="w-5 h-5 text-foreground" />
                      </div>
                      <span className="text-muted-foreground">Total Bill Amount</span>
                    </div>
                    <p className="text-3xl font-bold text-foreground flex items-center">
                      <IndianRupee className="w-7 h-7" />
                      {claimData.totalBill.toLocaleString()}
                    </p>
                  </HealthcareCardContent>
                </HealthcareCard>

                {/* Approved Amount */}
                <HealthcareCard variant="success" padding="lg">
                  <HealthcareCardContent>
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-10 h-10 rounded-xl bg-success/20 flex items-center justify-center">
                        <CheckCircle className="w-5 h-5 text-success" />
                      </div>
                      <span className="text-foreground">Approved Reimbursement</span>
                    </div>
                    <p className="text-4xl font-bold text-success flex items-center">
                      <IndianRupee className="w-8 h-8" />
                      {claimData.approvedAmount.toLocaleString()}
                    </p>
                  </HealthcareCardContent>
                </HealthcareCard>

                {/* Deductions */}
                <HealthcareCard variant="elevated" padding="lg">
                  <HealthcareCardHeader>
                    <HealthcareCardTitle className="flex items-center gap-2 text-base">
                      <Minus className="w-4 h-4 text-destructive" />
                      Deductions Breakdown
                    </HealthcareCardTitle>
                  </HealthcareCardHeader>
                  <HealthcareCardContent>
                    <div className="space-y-4">
                      {claimData.deductions.map((deduction, index) => (
                        <div key={index} className="pb-3 border-b border-border last:border-0 last:pb-0">
                          <div className="flex items-center justify-between mb-1">
                            <span className="font-medium text-foreground">{deduction.item}</span>
                            <span className="font-semibold text-destructive">
                              -₹{deduction.amount.toLocaleString()}
                            </span>
                          </div>
                          <p className="text-sm text-muted-foreground">{deduction.reason}</p>
                        </div>
                      ))}
                      <div className="pt-3 border-t-2 border-border">
                        <div className="flex items-center justify-between">
                          <span className="font-semibold text-foreground">Total Deductions</span>
                          <span className="font-bold text-destructive">
                            -₹{claimData.deductionAmount.toLocaleString()}
                          </span>
                        </div>
                      </div>
                    </div>
                  </HealthcareCardContent>
                </HealthcareCard>
              </motion.div>

              {/* Right Panel - AI Reasoning Timeline */}
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 }}
                className="lg:col-span-3"
              >
                <HealthcareCard variant="elevated" padding="lg" className="h-full">
                  <HealthcareCardHeader>
                    <HealthcareCardTitle className="flex items-center gap-2">
                      <Info className="w-5 h-5 text-primary" />
                      Why This Amount Was Approved
                    </HealthcareCardTitle>
                  </HealthcareCardHeader>
                  <HealthcareCardContent>
                    <div className="space-y-1">
                      {claimData.timeline.map((item, index) => (
                        <motion.div
                          key={index}
                          initial={{ opacity: 0, x: 10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.4 + index * 0.1 }}
                          className="relative pl-8 pb-6 last:pb-0"
                        >
                          {/* Timeline Line */}
                          {index < claimData.timeline.length - 1 && (
                            <div className="absolute left-[11px] top-6 bottom-0 w-0.5 bg-success/30" />
                          )}
                          
                          {/* Timeline Dot */}
                          <div className="absolute left-0 top-0.5 w-6 h-6 rounded-full bg-success/20 flex items-center justify-center">
                            <CheckCircle className="w-4 h-4 text-success" />
                          </div>

                          <div>
                            <div className="flex items-center gap-3 mb-1">
                              <h4 className="font-semibold text-foreground">{item.step}</h4>
                              <span className="text-xs text-muted-foreground bg-muted px-2 py-0.5 rounded-full">
                                {item.time}
                              </span>
                            </div>
                            <p className="text-sm text-muted-foreground">
                              {item.step === "Verification Agent" && result.verification?.notes?.join(" ")}
                              {item.step === "Eligibility Agent" && result.eligibility?.warnings?.join(" ")}
                              {item.step === "Deduction Agent" && result.deductions?.summary}
                              {item.step === "Risk Assessment" && result.riskAssessment?.reasons?.join(" ")}
                            </p>

                          </div>
                        </motion.div>
                      ))}
                    </div>

                    {/* Summary Box */}
                    <div className="mt-8 p-4 bg-card/50 rounded-xl border border-border">
                      <h4 className="font-semibold text-foreground mb-2">Summary</h4>
                      <p className="text-sm text-muted-foreground">
                        {result.deductions?.summary ||
                          `Out of ₹${claimData.totalBill.toLocaleString()}, 
                          payable amount is ₹${claimData.approvedAmount.toLocaleString()} 
                          after applicable deductions.`}
                      </p>

                    </div>
                  </HealthcareCardContent>
                </HealthcareCard>
              </motion.div>
            </div>

            {/* Action Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="mt-8"
            >
              <HealthcareCard variant="sage" padding="lg">
                <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                  <div>
                    <h3 className="text-lg font-semibold text-foreground mb-1">
                      Download AI Audit Report
                    </h3>
                    <p className="text-muted-foreground text-sm">
                      Get a detailed breakdown of agent verification logs, policy reasoning, and final deduction calculations.
                    </p>
                  </div>
                  <div className="flex gap-3">
                    <HealthcareButton variant="outline" onClick={() => navigate("/dashboard")}>
                      Back to Dashboard
                    </HealthcareButton>
                    <HealthcareButton variant="hero" onClick={handleDownloadDossier} className="group">
                      <Download className="w-5 h-5" />
                      Download Report
                      <ArrowRight className="w-5 h-5 transition-transform group-hover:translate-x-1" />
                    </HealthcareButton>
                  </div>
                </div>
              </HealthcareCard>
            </motion.div>
          </div>
        </div>
      </main>

      <ChatBot />
    </div>
  );
};

export default ClaimDecision;
